// PurrCrafts Product Catalog
// Handmade pipecleaner flowers & cute miniatures crafted with love

const PRODUCTS_DATA = [
  {
    id: "pc-01",
    name: "Sunset Pastel Tulip Bouquet (5 Stems)",
    category: "bouquets",
    categoryName: "Bouquets & Pots",
    price: 799,
    originalPrice: 999,
    badge: "🌸 Bestseller",
    badgeColor: "bg-rose-100 text-rose-700 border-rose-200",
    rating: 4.9,
    reviewsCount: 38,
    shortDescription: "Delicate hand-twisted chenille tulips in gentle gradient sunset shades.",
    fullDescription: "A dreamy cluster of 5 handmade chenille pipe cleaner tulips featuring soft blush pink, butter peach, and cream tones. Each petal is individually twisted and sculpted for a velvety, soft-touch texture that will stay forever fresh without water or sunlight.",
    materials: "Premium velvety chenille stems, floral wire core, floristry tape, waterproof Korean wrapping paper & luxury satin ribbon",
    dimensions: "Height: ~32 cm | Bouquet Width: ~18 cm",
    craftTime: "Handmade (approx. 2.5 hours of delicate twisting)",
    images: [
      "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Blush Pink", "Vanilla Cream", "Sage Ribbon", "Lilac Silk"],
    inStock: true,
    tags: ["tulips", "everlasting", "bouquet", "pastel", "gift"]
  },
  {
    id: "pc-02",
    name: "Eternal Sunshine Daisy & Sunflower Bunch",
    category: "bouquets",
    categoryName: "Bouquets & Pots",
    price: 899,
    originalPrice: 1149,
    badge: "☀️ Cheerful Pick",
    badgeColor: "bg-amber-100 text-amber-700 border-amber-200",
    rating: 5.0,
    reviewsCount: 44,
    shortDescription: "Vibrant pipe cleaner sunflowers paired with happy white daisies.",
    fullDescription: "Bring permanent warmth to any desk or bedside table! Features 1 large golden-yellow sunflower with intricate textured chenille seed head, flanked by 3 happy white daisies and miniature baby's breath accents.",
    materials: "Chenille pipe cleaners, flexible florist wire, eco-friendly Kraft wrapping & twine/satin bow",
    dimensions: "Height: ~34 cm | Bouquet Width: ~20 cm",
    craftTime: "Handmade with love (approx. 3 hours)",
    images: [
      "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Warm Honey", "Rustic Twine", "Forest Green", "Crisp White"],
    inStock: true,
    tags: ["sunflower", "daisy", "bright", "cheerful", "desk-decor"]
  },
  {
    id: "pc-03",
    name: "Tiny Calico Kitten Miniature Desk Companion",
    category: "miniatures",
    categoryName: "Cute Miniatures",
    price: 449,
    originalPrice: 549,
    badge: "🐾 Signature Cat",
    badgeColor: "bg-purple-100 text-purple-700 border-purple-200",
    rating: 5.0,
    reviewsCount: 52,
    shortDescription: "Adorably sculpted fluffy pipe cleaner cat with tiny bell collar & fish charm.",
    fullDescription: "Our signature PurrCrafts mascot! Each miniature calico kitten is hand-sculpted strand by strand from soft chenille stems with little perky ears, whisker details, a curled tail, and a sweet miniature brass bell collar.",
    materials: "Multi-tone chenille pipe cleaners, tiny glass eyes, mini brass bell, velvet ribbon collar",
    dimensions: "Height: ~7 cm | Width: ~5 cm",
    craftTime: "Handmade (approx. 2 hours of micro-sculpting)",
    images: [
      "https://images.unsplash.com/photo-1535268645242-68b563b98b79?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Red Bell Collar", "Sky Blue Bell Collar", "Pink Bell Collar"],
    inStock: true,
    tags: ["kitten", "miniature", "cat", "desk pet", "purrcrafts"]
  },
  {
    id: "pc-04",
    name: "Potted Dancing Daisy in Pastel Ceramic Cup",
    category: "pots",
    categoryName: "Single Stems & Potted",
    price: 499,
    originalPrice: 650,
    badge: "🪴 Desk Ready",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    rating: 4.8,
    reviewsCount: 29,
    shortDescription: "A cheerful handmade daisy rooted in an adorable mini pastel ceramic pot.",
    fullDescription: "A no-fuss desk plant that will never dry out! Flexible stem allows you to pose the blossom in any cute angle. Topped with fuzzy moss and planted securely inside a mini pastel ceramic pot.",
    materials: "Chenille craft stems, miniature ceramic pot, simulated green craft moss, weighted plaster base",
    dimensions: "Height: ~16 cm | Pot Diameter: ~6.5 cm",
    craftTime: "Handcrafted (approx. 1.5 hours)",
    images: [
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Mint Green Pot", "Pastel Pink Pot", "Cream Pot"],
    inStock: true,
    tags: ["daisy", "potted", "ceramic", "desk plant"]
  },
  {
    id: "pc-05",
    name: "Lavender Dreams & Baby's Breath Posy",
    category: "bouquets",
    categoryName: "Bouquets & Pots",
    price: 699,
    originalPrice: 850,
    badge: "💜 Calming Aesthetic",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-200",
    rating: 4.9,
    reviewsCount: 31,
    shortDescription: "Deep lavender spikes & lilac chenille blossoms tied in sheer organza.",
    fullDescription: "Inspired by French lavender fields, this relaxing bundle features 6 velvety lavender stems with textured bead-like chenille segments, complemented with white accent sprays. Perfect for bedroom decor or a calming work desk.",
    materials: "Velvet chenille stems in 3 shades of lilac and violet, floral stem wire, organza bow",
    dimensions: "Height: ~28 cm | Width: ~14 cm",
    craftTime: "Handmade (approx. 2 hours)",
    images: [
      "https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Lavender Organza", "White Lace", "Silver Grey"],
    inStock: true,
    tags: ["lavender", "purple", "calm", "everlasting", "aesthetic"]
  },
  {
    id: "pc-06",
    name: "Fluffy Bunny with Strawberry Charm Keychain",
    category: "miniatures",
    categoryName: "Cute Miniatures",
    price: 349,
    originalPrice: 449,
    badge: "🍓 Cute Keychain",
    badgeColor: "bg-pink-100 text-pink-700 border-pink-200",
    rating: 4.9,
    reviewsCount: 67,
    shortDescription: "Ultra-soft pipe cleaner bunny holding a tiny pink strawberry on a gold clasp.",
    fullDescription: "Take cuteness wherever you go! Hand-twisted from plush white chenille, this chubby bunny holds an intricately crafted mini strawberry. Attached to a luxury lobster clasp keychain for your bag, tote, or keys.",
    materials: "Extra fluffy chenille stems, safety bead eyes, gold-plated lobster keychain clasp",
    dimensions: "Miniature: ~6 cm | Keychain total length: ~12 cm",
    craftTime: "Handmade (approx. 1.5 hours)",
    images: [
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1535268645242-68b563b98b79?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Gold Hardware", "Rose Gold Hardware", "Silver Hardware"],
    inStock: true,
    tags: ["bunny", "keychain", "strawberry", "bag charm", "cute"]
  },
  {
    id: "pc-07",
    name: "Sweetheart Keepsake Gift Box (Kitten + 3 Tulips)",
    category: "gift_sets",
    categoryName: "Gift Sets & Hampers",
    price: 1299,
    originalPrice: 1599,
    badge: "🎁 Deluxe Gift Box",
    badgeColor: "bg-rose-100 text-rose-800 border-rose-300",
    rating: 5.0,
    reviewsCount: 26,
    shortDescription: "Gift-ready presentation box with mini handcrafted cat & 3 eternal tulips.",
    fullDescription: "The ultimate gifting delight from PurrCrafts! Includes 3 graceful pastel chenille tulips, 1 miniature handmade kitten mascot, fragrant craft shreds, fairy-light string (included!), and a handwritten personalized note card in a rigid magnetic gift box.",
    materials: "Magnetic luxury gift box, handmade pipe cleaner flowers & kitten, LED fairy lights (battery included), satin bow",
    dimensions: "Box Size: 25 x 18 x 10 cm",
    craftTime: "Handmade (approx. 4 hours total crafting)",
    images: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1535268645242-68b563b98b79?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Blush Pink Luxury", "Champagne Gold", "Crimson Velvet"],
    inStock: true,
    tags: ["gift set", "box", "lights", "tulips", "kitten", "birthday"]
  },
  {
    id: "pc-08",
    name: "Single Blushing Rose in Kraft Sleeve",
    category: "pots",
    categoryName: "Single Stems & Potted",
    price: 299,
    originalPrice: 399,
    badge: "🌹 Sweet Gesture",
    badgeColor: "bg-red-100 text-red-700 border-red-200",
    rating: 4.8,
    reviewsCount: 19,
    shortDescription: "A singular, beautifully sculpted pipe cleaner rose with leaf accents.",
    fullDescription: "A poetic, lasting token of affection. One sculpted scarlet or blush rose with layered chenille petals, dual green leaves, and wrapped individually in a clear window Kraft sleeve with a 'Handmade Just For You' seal.",
    materials: "Rich crimson/blush chenille stems, floral wire, Kraft cone sleeve",
    dimensions: "Length: ~30 cm | Flower Diameter: ~8 cm",
    craftTime: "Handmade (approx. 1 hour)",
    images: [
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Velvet Crimson", "Pastel Pink", "Classic Black Satin"],
    inStock: true,
    tags: ["rose", "single stem", "romantic", "valentines", "keepsake"]
  },
  {
    id: "pc-09",
    name: "Sleepy Matcha Frog Desk Companion",
    category: "miniatures",
    categoryName: "Cute Miniatures",
    price: 399,
    originalPrice: 499,
    badge: "🐸 Cozy Desk Pet",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    rating: 4.9,
    reviewsCount: 35,
    shortDescription: "A serene little green frog with pink cheeks resting on a mini lilypad.",
    fullDescription: "Meet the chillest desk buddy you'll ever have! Sculpted from earthy matcha-green chenille with blushy pink embroidered cheeks, sitting comfortably on its own mini felt lilypad coaster.",
    materials: "Chenille craft stems, felt pad base, pink acrylic blush detail",
    dimensions: "Height: ~5.5 cm | Width: ~6 cm",
    craftTime: "Handmade (approx. 1.5 hours)",
    images: [
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Matcha Green", "Forest Olive", "Lotus Pink"],
    inStock: true,
    tags: ["frog", "miniature", "desk companion", "cute", "green"]
  },
  {
    id: "pc-10",
    name: "Whimsical Wildflower Bouquet in Frosted Mason Jar",
    category: "pots",
    categoryName: "Single Stems & Potted",
    price: 949,
    originalPrice: 1199,
    badge: "🌿 Cottagecore",
    badgeColor: "bg-stone-100 text-stone-700 border-stone-200",
    rating: 5.0,
    reviewsCount: 22,
    shortDescription: "A cozy arrangement of daisies, lavender, and cosmos in a rustic glass jar.",
    fullDescription: "Brings cottagecore charm straight into your room. An eclectic, whimsical mix of 7 handmade stems including white daisies, lavender stalks, soft pink cosmos, and green eucalyptus sprays styled in a frosted glass jar with twine collar.",
    materials: "Velvet chenille stems, frosted glass mason jar, natural jute twine",
    dimensions: "Total Height: ~28 cm | Jar Diameter: ~8 cm",
    craftTime: "Handmade (approx. 3.5 hours)",
    images: [
      "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Natural Jute", "Sage Silk", "Lace White"],
    inStock: true,
    tags: ["wildflowers", "mason jar", "cottagecore", "rustic", "decor"]
  },
  {
    id: "pc-11",
    name: "Cherry Blossom Spring Bloom Bouquet",
    category: "bouquets",
    categoryName: "Bouquets & Pots",
    price: 849,
    originalPrice: 1050,
    badge: "🌸 Seasonal Favorite",
    badgeColor: "bg-pink-100 text-pink-700 border-pink-200",
    rating: 4.9,
    reviewsCount: 41,
    shortDescription: "Soft sakura cherry blossom branches with multi-petaled blush flowers.",
    fullDescription: "Celebrate eternal spring with these exquisite handmade sakura stems. Features over 15 individual small blooming florets and budding tips in powder pink and ivory with golden stamen accents.",
    materials: "Pastel chenille stems, golden stamen threads, realistic textured branch wrapping",
    dimensions: "Height: ~38 cm | Branch spread: ~22 cm",
    craftTime: "Handmade (approx. 3.5 hours)",
    images: [
      "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Cherry Blossom Pink", "Ivory Cream", "Sakura Gold"],
    inStock: true,
    tags: ["cherry blossom", "sakura", "spring", "pink", "aesthetic"]
  },
  {
    id: "pc-12",
    name: "Graduation Celebration Bouquet with Cap & Diploma",
    category: "gift_sets",
    categoryName: "Gift Sets & Hampers",
    price: 1199,
    originalPrice: 1499,
    badge: "🎓 Graduation Special",
    badgeColor: "bg-blue-100 text-blue-700 border-blue-200",
    rating: 5.0,
    reviewsCount: 18,
    shortDescription: "Sunflower & tulip bouquet accented with a miniature graduation cap & scroll.",
    fullDescription: "The most memorable gift for graduates! Fresh flowers wither in days, but this graduation bouquet will commemorate their milestone forever. Comes with a bright sunflower, 2 victory tulips, a miniature chenille mortarboard cap with tassel, and a tied scroll.",
    materials: "Chenille stems, miniature felt grad cap with gold tassel, Korean waterproof wrap",
    dimensions: "Height: ~36 cm | Bouquet Width: ~22 cm",
    craftTime: "Handmade (approx. 3.5 hours)",
    images: [
      "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80"
    ],
    ribbonOptions: ["Graduation Navy", "Gold Honor", "Royal Crimson"],
    inStock: true,
    tags: ["graduation", "gift", "sunflower", "milestone", "keepsake"]
  }
];

const CATEGORIES = [
  { id: "all", name: "All Creations", icon: "sparkles", count: 12 },
  { id: "bouquets", name: "Bouquets & Pots", icon: "flower-2", count: 4 },
  { id: "pots", name: "Single Stems & Potted", icon: "sprout", count: 3 },
  { id: "miniatures", name: "Cute Miniatures", icon: "paw-print", count: 3 },
  { id: "gift_sets", name: "Gift Sets & Hampers", icon: "gift", count: 2 }
];
